# Generated by Django 5.0 on 2024-01-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('year_joined', models.IntegerField()),
                ('year_Ended', models.IntegerField()),
                ('grade_attained', models.CharField(max_length=55)),
                ('certificate_earned', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intrests',
            fields=[
                ('intrests_id', models.AutoField(primary_key=True, serialize=False)),
                ('intrests_name', models.CharField(max_length=255, unique=True)),
                ('intrests_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingParadigm',
            fields=[
                ('paradigm_id', models.AutoField(primary_key=True, serialize=False)),
                ('paradigm_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255)),
                ('percentage_coverage', models.IntegerField()),
                ('programming_paradigm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.programmingparadigm')),
            ],
        ),
    ]
