# Generated by Django 5.0 on 2024-01-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_delete_programminglanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255)),
                ('percentage_coverage', models.IntegerField()),
            ],
        ),
    ]
