# Generated by Django 5.0 on 2024-01-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
