# Generated by Django 5.0 on 2024-01-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_delete_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('work_title', models.CharField(max_length=266)),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
    ]
