# Generated by Django 5.0 on 2024-01-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
