# Generated by Django 5.0 on 2024-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
